# Generated by Django 3.1.1 on 2020-09-21 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OverviewData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Category')),
                ('submit_type', models.CharField(blank=True, max_length=50, verbose_name='Submit Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('premium_total', models.IntegerField(blank=True, default=0, verbose_name='Premium Total')),
                ('premium_total_auth', models.IntegerField(blank=True, default=0, verbose_name='Authority Premium Total')),
                ('premium_total_com', models.IntegerField(blank=True, default=0, verbose_name='Commodity Premium Total')),
                ('premium_percent_auth', models.IntegerField(blank=True, default=0, verbose_name='Authority Premium Percent')),
                ('premium_percent_com', models.IntegerField(blank=True, default=0, verbose_name='Commodity Premium Percent')),
                ('dwp', models.IntegerField(blank=True, default=0, verbose_name='Direct Written Premium')),
                ('status', models.CharField(blank=True, max_length=10, verbose_name='Status')),
                ('premium_growth_actual', models.IntegerField(blank=True, default=0, verbose_name='Actual Premium Growth')),
                ('premium_growth_target', models.IntegerField(blank=True, default=0, verbose_name='Target Premium Growth')),
                ('policy_count_actual', models.IntegerField(blank=True, default=0, verbose_name='Actual Inforce Policy Count')),
                ('policy_count_target', models.IntegerField(blank=True, default=0, verbose_name='Target Inforce Policy Count')),
                ('dwp_per_policy_actual', models.IntegerField(blank=True, default=0, verbose_name='Actual Dwp Per In-Force Policy')),
                ('dwp_per_policy_target', models.IntegerField(blank=True, default=0, verbose_name='Target Dwp Per In-Force Policy')),
                ('loss_ratio_actual', models.IntegerField(blank=True, default=0, verbose_name='Actual Loss Ratio Non-CAT')),
                ('loss_ratio_target', models.IntegerField(blank=True, default=0, verbose_name='Actual Loss Ratio Non-CAT')),
                ('loss_ratio_cat_actual', models.IntegerField(blank=True, default=0, verbose_name='Actual Loss Ratio CAT')),
                ('loss_ratio_cat_target', models.IntegerField(blank=True, default=0, verbose_name='Target Loss Ratio CAT')),
                ('loss_ratio_large_actual', models.IntegerField(blank=True, default=0, verbose_name='Actual Loss Ratio Large Loss')),
                ('loss_ratio_large_target', models.IntegerField(blank=True, default=0, verbose_name='Targe Loss Ratio Large Loss')),
                ('claim_count_actual', models.IntegerField(blank=True, default=0, verbose_name='Actual Claim Count')),
                ('claim_count_target', models.IntegerField(blank=True, default=0, verbose_name='Target Claim Count')),
                ('loss_size_avg_actual', models.IntegerField(blank=True, default=0, verbose_name='Actual Average Loss Size')),
                ('loss_size_avg_target', models.IntegerField(blank=True, default=0, verbose_name='Target Average Loss Size')),
                ('commodity_count_total', models.IntegerField(blank=True, default=0, verbose_name='Commodity Count')),
                ('commodity_dwp_percent', models.IntegerField(blank=True, default=0, verbose_name='Commodity DWP Percent')),
                ('submission_count_total', models.IntegerField(blank=True, default=0, verbose_name='Submission Count')),
                ('submission_dwp_percent', models.IntegerField(blank=True, default=0, verbose_name='Submission DWP Percent')),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
        migrations.CreateModel(
            name='PolicyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Comment')),
                ('policy_nb', models.CharField(max_length=10, verbose_name='Policy Number')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True, verbose_name='Created By')),
                ('topic', models.CharField(blank=True, max_length=20, null=True, verbose_name='Topic')),
            ],
            options={
                'verbose_name_plural': 'Segment Comments',
            },
        ),
        migrations.CreateModel(
            name='CommentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Comment')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Created By')),
                ('topic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Topic')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.overviewdata')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='AlertData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Alert Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Alert Description')),
                ('recommendation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Recommendation')),
                ('recommendation_desc', models.TextField(blank=True, null=True, verbose_name='Recommendation Description')),
                ('alert_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Alert Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('created_by', models.CharField(max_length=50, verbose_name='Created By')),
                ('condition', models.CharField(blank=True, max_length=50, null=True, verbose_name='Operation')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('reviewer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reviewer')),
                ('involved', models.CharField(blank=True, max_length=50, null=True, verbose_name='Others Involved')),
                ('action_taken', models.TextField(blank=True, null=True, verbose_name='Action Taken')),
                ('completed_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Status')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.overviewdata', verbose_name='Targe Data')),
            ],
            options={
                'verbose_name_plural': 'Alerts',
            },
        ),
    ]
